using Parse.FrontEnd.RegularGrammar;
using System;
using System.Collections.Generic;
using System.Text;

namespace Parse.FrontEnd
{
    public class AutoGeneratedNTStore
    {
        static public Dictionary<Symbol, NonTerminal> OptionList { get; } = new Dictionary<Symbol, NonTerminal>();
        static public Dictionary<Symbol, NonTerminal> ZeroOrMoreList { get; } = new Dictionary<Symbol, NonTerminal>();
        static public Dictionary<Symbol, NonTerminal> OneOrMoreList { get; } = new Dictionary<Symbol, NonTerminal>();
    }
}
