//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parse.FrontEnd.AJ.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlarmCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlarmCodes() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parse.FrontEnd.AJ.Properties.AlarmCodes", typeof(AlarmCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The &apos;{1}&apos; definition is included in the &apos;{0}&apos; type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AJ0026 {
            get {
                return ResourceManager.GetString("AJ0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The member name can&apos;t same with the outer name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AJ0027 {
            get {
                return ResourceManager.GetString("AJ0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It can&apos;t be come the expression because the return type of function is void.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AJ0028 {
            get {
                return ResourceManager.GetString("AJ0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It must be come the expression because the return type of function is not void.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AJ0029 {
            get {
                return ResourceManager.GetString("AJ0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} type can&apos;t convert to {1} type. please return type of function.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AJ0030 {
            get {
                return ResourceManager.GetString("AJ0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is already defined.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0000 {
            get {
                return ResourceManager.GetString("MCL0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not defined.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0001 {
            get {
                return ResourceManager.GetString("MCL0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value can not be changed because {0} is the constant type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0002 {
            get {
                return ResourceManager.GetString("MCL0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It can not be allocated because the data type differs.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0003 {
            get {
                return ResourceManager.GetString("MCL0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lvalue have to be modifiable format.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0004 {
            get {
                return ResourceManager.GetString("MCL0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} variable that not initialized is using.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0005 {
            get {
                return ResourceManager.GetString("MCL0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Integer or enum type has to be to expression.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0006 {
            get {
                return ResourceManager.GetString("MCL0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buffer overflow fired while write {0}. writable byte is {1} but in fact write {2} byte.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0007 {
            get {
                return ResourceManager.GetString("MCL0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operand of Inc or Dec operator has to be variable, property or indexer.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0008 {
            get {
                return ResourceManager.GetString("MCL0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The {0} identifier was already defined in the current block.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0009 {
            get {
                return ResourceManager.GetString("MCL0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It was failed to struct Sdts nodes.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0010 {
            get {
                return ResourceManager.GetString("MCL0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The calculation &apos;{0}&apos; is not applicated for the operand &apos;{1}&apos; and &apos;{2}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0011 {
            get {
                return ResourceManager.GetString("MCL0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operand of the inc or dec has to be variable, property or indexer.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0012 {
            get {
                return ResourceManager.GetString("MCL0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operator &apos;{0}&apos; is not applicated to {1} type operand.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0013 {
            get {
                return ResourceManager.GetString("MCL0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The member &apos;{0}&apos; is not used as method.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0014 {
            get {
                return ResourceManager.GetString("MCL0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is not overload method &apos;{1}&apos; that use parameter {0} count.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0015 {
            get {
                return ResourceManager.GetString("MCL0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is not argument for parameter &apos;{1}&apos; that need in the &apos;{0}&apos; method.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0016 {
            get {
                return ResourceManager.GetString("MCL0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It can&apos;t be declared using identifier that defined in macro.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0017 {
            get {
                return ResourceManager.GetString("MCL0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The macro can&apos;t be included own identifier.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0018 {
            get {
                return ResourceManager.GetString("MCL0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The reverse reference can be used only if type is address type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0019 {
            get {
                return ResourceManager.GetString("MCL0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;{0}&apos; type can&apos;t be used for variable type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0020 {
            get {
                return ResourceManager.GetString("MCL0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;{1}&apos; definition is included in the &apos;{0}&apos; namespace.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0021 {
            get {
                return ResourceManager.GetString("MCL0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;!&apos; operator can be applied to only &apos;bool&apos; type operand.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0022 {
            get {
                return ResourceManager.GetString("MCL0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; operator can&apos;t be applied to &apos;{1}&apos; and &apos;{2}&apos; type operand.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0023 {
            get {
                return ResourceManager.GetString("MCL0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type &apos;{0}&apos; and &apos;{1}&apos; can&apos;t be compared.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0024 {
            get {
                return ResourceManager.GetString("MCL0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It can&apos;t convert from {0} type to {1} type implicitly.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MCL0025 {
            get {
                return ResourceManager.GetString("MCL0025", resourceCulture);
            }
        }
    }
}
