using ParsingLibrary.Datas.RegularGrammar;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ParsingLibrary.Utilities
{
    public class KeyManager
    {
        private Dictionary<UInt32, string> terminalKeyDic = new Dictionary<uint, string>();
        private Dictionary<UInt32, string> nonTerminalKeyDic = new Dictionary<uint, string>();

        private UInt32 terminalKey = 1000000;                   // 1000000 ~ 1999999
        private UInt32 nonTerminalKey = 2000000;            // 2000000 ~ 2999999
        private UInt32 autogeneratedNTKey = 3000000;    // 3000000 ~ 3999999

        public UInt32 MarkerSymbolKey { get; } = 1;
        public UInt32 EpsilonKey { get; } = 2;
        public UInt32 NotDefinedKey { get; } = 3;


        public void AllocateUniqueKey(Terminal item)
        {
            if (terminalKeyDic.ContainsValue(item.Value))
                item.uniqueKey = terminalKeyDic.FirstOrDefault(x => x.Value == item.Value).Key;
            else
            {
                terminalKeyDic.Add(terminalKey, item.Value);
                item.uniqueKey = terminalKey++;
            }
        }

        public void AllocateUniqueKey(NonTerminal item)
        {
            if (nonTerminalKeyDic.ContainsValue(item.Name))
                item.uniqueKey = nonTerminalKeyDic.FirstOrDefault(x => x.Value == item.Name).Key;
            else
            {
                if(item.AutoGenerated)
                {
                    nonTerminalKeyDic.Add(this.autogeneratedNTKey, item.Name);
                    item.uniqueKey = this.autogeneratedNTKey++;
                }
                else
                {
                    nonTerminalKeyDic.Add(this.nonTerminalKey, item.Name);
                    item.uniqueKey = this.nonTerminalKey++;
                }
            }
        }

        public void Remove(NonTerminal nonTerminal)
        {
            var key = this.nonTerminalKeyDic.FirstOrDefault(x => x.Value == nonTerminal.Name).Key;
            this.nonTerminalKeyDic.Remove(key);
        }
    }
}
