using Xunit;

// The grammar/parser build path currently relies on PROCESS-GLOBAL static state
// (Parse.FrontEnd.AutoGenerator + AutoGeneratedNTStore), so two grammars cannot be
// constructed concurrently without corrupting each other. Until the Phase-1 refactor
// moves that state onto the Grammar instance, tests MUST run sequentially.
//
// This attribute is itself a living note about that blocker: when the static state is
// removed, this line can go away and the suite can run in parallel.
[assembly: CollectionBehavior(DisableTestParallelization = true)]
