//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandPrompt.Builder.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandPrompt.Builder.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add the project to solution file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The project was added to solution.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddProjectSuccess {
            get {
                return ResourceManager.GetString("AddProjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The program to construct the build solution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AJBuild {
            get {
                return ResourceManager.GetString("AJBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show detail contents related to the target architecture.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Arch {
            get {
                return ResourceManager.GetString("Arch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify target architecture. you can see the supported architecture type through the command ajbuild arch --list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ArchOption {
            get {
                return ResourceManager.GetString("ArchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify ARM architecture.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ArmArch {
            get {
                return ResourceManager.GetString("ArmArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify AVR architecture.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AvrArch {
            get {
                return ResourceManager.GetString("AvrArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulld the project and dependency to binary file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Define build configuration. The basic value is the debug, the supported build configuration is the debug, release.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BuildConfig {
            get {
                return ResourceManager.GetString("BuildConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The project file or solution file to build. If the project file or solution file is not specified search the project file or solution file in the current direcotry and if found use it.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BuildTarget {
            get {
                return ResourceManager.GetString("BuildTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a library project.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateLibraryProject {
            get {
                return ResourceManager.GetString("CreateLibraryProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project file was created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateProjectSuccess {
            get {
                return ResourceManager.GetString("CreateProjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create solution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateSolution {
            get {
                return ResourceManager.GetString("CreateSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solution file was created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateSolutionSuccess {
            get {
                return ResourceManager.GetString("CreateSolutionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a start project.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateStartProject {
            get {
                return ResourceManager.GetString("CreateStartProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no project file in the specified path or there are the project files 2 more than.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorReadProject {
            get {
                return ResourceManager.GetString("ErrorReadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no solution file in the specified path or there are the solution files 2 more than.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorReadSolution {
            get {
                return ResourceManager.GetString("ErrorReadSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List the supported architecture list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListArch {
            get {
                return ResourceManager.GetString("ListArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List all project of solution file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListProject {
            get {
                return ResourceManager.GetString("ListProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List a template included specified template name. if the name is not specified list all templates.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListTemplate {
            get {
                return ResourceManager.GetString("ListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new project, the configure file or solution from the specified template과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewCommand {
            get {
                return ResourceManager.GetString("NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The position to deploy the generated output, basis value is current directory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the display format.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OutputFormat {
            get {
                return ResourceManager.GetString("OutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove the project from solution file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RemoveProject {
            get {
                return ResourceManager.GetString("RemoveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The project was removed from the solution.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RemoveProjectSuccess {
            get {
                return ResourceManager.GetString("RemoveProjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List or modify projects of solution file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Sln {
            get {
                return ResourceManager.GetString("Sln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The template to instantiate when the command is invoked. Each template might have specific options you can pass. For more information, see Template options. You can run ajbuild new --list to see a list of all installed templates.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show version information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
