//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationLayer.WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationLayer.WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _Edit {
            get {
                return ResourceManager.GetString("_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _File {
            get {
                return ResourceManager.GetString("_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All close except this window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllCloseExceptThisWindow {
            get {
                return ResourceManager.GetString("AllCloseExceptThisWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File aleady exist replace it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlreadyExistFile {
            get {
                return ResourceManager.GetString("AlreadyExistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canonical Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CanonicalTable {
            get {
                return ResourceManager.GetString("CanonicalTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create directory for solution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateSolutionDir {
            get {
                return ResourceManager.GetString("CreateSolutionDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Documentation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentDocumentation {
            get {
                return ResourceManager.GetString("CurrentDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentProject {
            get {
                return ResourceManager.GetString("CurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will really delete it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Existing Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExistItem {
            get {
                return ResourceManager.GetString("ExistItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explanation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grammar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Grammar {
            get {
                return ResourceManager.GetString("Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grammar information window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GrammarInfoWindow {
            get {
                return ResourceManager.GetString("GrammarInfoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Micro Controller과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MicroController {
            get {
                return ResourceManager.GetString("MicroController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Create과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ok과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open folder from explorer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenFolderFromExplorer {
            get {
                return ResourceManager.GetString("OpenFolderFromExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parse Tree과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ParseTree {
            get {
                return ResourceManager.GetString("ParseTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parsing Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ParsingTable {
            get {
                return ResourceManager.GetString("ParsingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project/Solution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProjectOrSolution {
            get {
                return ResourceManager.GetString("ProjectOrSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProjectPath {
            get {
                return ResourceManager.GetString("ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solution Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SolutionPath {
            get {
                return ResourceManager.GetString("SolutionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whole Solution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WholeSolution {
            get {
                return ResourceManager.GetString("WholeSolution", resourceCulture);
            }
        }
    }
}
