//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parse.FrontEnd.Parsers.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parse.FrontEnd.Parsers.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The action information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ActionInfo {
            get {
                return ResourceManager.GetString("ActionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operation {0} is performed after back-tracking.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BackTracking {
            get {
                return ResourceManager.GetString("BackTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   can&apos;t shift과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CantShift {
            get {
                return ResourceManager.GetString("CantShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An input symbol과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InputSymbol {
            get {
                return ResourceManager.GetString("InputSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert a virtual token : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InsertVirtualToken {
            get {
                return ResourceManager.GetString("InsertVirtualToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   must come here과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MustCome {
            get {
                return ResourceManager.GetString("MustCome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   recover with private LR handler ix : {0}, token type : {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecoverWithLRHandler {
            get {
                return ResourceManager.GetString("RecoverWithLRHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   recover with panic mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecoverWithPanicMode {
            get {
                return ResourceManager.GetString("RecoverWithPanicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed a recovery과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecoveryFailed {
            get {
                return ResourceManager.GetString("RecoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The recovery information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecoveryInfo {
            get {
                return ResourceManager.GetString("RecoveryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   successed a recovery과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecoverySuccessed {
            get {
                return ResourceManager.GetString("RecoverySuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rollback as much as {0} count because can&apos;t shift.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RemoveParsingUnits {
            get {
                return ResourceManager.GetString("RemoveParsingUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   replace to a virtual token : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplaceVirtualToken {
            get {
                return ResourceManager.GetString("ReplaceVirtualToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   skip this token과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SkipToken {
            get {
                return ResourceManager.GetString("SkipToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The stack after parsing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StackAfterParsing {
            get {
                return ResourceManager.GetString("StackAfterParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The stack before parsing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StackBeforeParsing {
            get {
                return ResourceManager.GetString("StackBeforeParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The stack for ast과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StackForAst {
            get {
                return ResourceManager.GetString("StackForAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   try to adjust a stack with this token과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TryAdjustStackWithThisToken {
            get {
                return ResourceManager.GetString("TryAdjustStackWithThisToken", resourceCulture);
            }
        }
    }
}
