//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parse.FrontEnd.DrawingSupport.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parse.FrontEnd.DrawingSupport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Accesser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Accesser {
            get {
                return ResourceManager.GetString("Accesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comma (,)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control statement과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ControlStatement {
            get {
                return ResourceManager.GetString("ControlStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Curly brace ({ })과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurlyBrace {
            get {
                return ResourceManager.GetString("CurlyBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Defined data type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DefinedDataType {
            get {
                return ResourceManager.GetString("DefinedDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Digit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Digit {
            get {
                return ResourceManager.GetString("Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decimal number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Digit10 {
            get {
                return ResourceManager.GetString("Digit10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hexadecimal number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Digit16 {
            get {
                return ResourceManager.GetString("Digit16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binary number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Digit2 {
            get {
                return ResourceManager.GetString("Digit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Octal number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Digit8 {
            get {
                return ResourceManager.GetString("Digit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etc keyword과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EtcKeyword {
            get {
                return ResourceManager.GetString("EtcKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etc operator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EtcOperator {
            get {
                return ResourceManager.GetString("EtcOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Identifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LineComment {
            get {
                return ResourceManager.GetString("LineComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bracket (( ))과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Parenthesis {
            get {
                return ResourceManager.GetString("Parenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat statement과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RepeatStatement {
            get {
                return ResourceManager.GetString("RepeatStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scope comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ScopeComment {
            get {
                return ResourceManager.GetString("ScopeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Special word과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpecialWord {
            get {
                return ResourceManager.GetString("SpecialWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Squre ([ ])과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Squre {
            get {
                return ResourceManager.GetString("Squre", resourceCulture);
            }
        }
    }
}
