//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandPrompt.Compiler.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandPrompt.Compiler.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AJ Compiler과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ajc {
            get {
                return ResourceManager.GetString("Ajc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create the assembly file after compile.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compile and generate obj file. The obj file name created is the same as the source file name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file name to compile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileNameToCompile {
            get {
                return ResourceManager.GetString("FileNameToCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The input file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The output file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The full path with the project name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProjectFullPath {
            get {
                return ResourceManager.GetString("ProjectFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create to binary file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToBinary {
            get {
                return ResourceManager.GetString("ToBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create to library file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToLibrary {
            get {
                return ResourceManager.GetString("ToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show version information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
