using Parse.FrontEnd.RegularGrammar;
using System;

namespace Parse.FrontEnd
{
    public class AutoGenerator
    {
        private static int autoGeneratedIdx = 1;
        private static KeyManager keyManager = null;

        public static Action<NonTerminal> CreateAutoGenerateNT { get; set; } = null;

        public static void SetKeyManager(KeyManager keyManager)
        {
            AutoGenerator.keyManager = keyManager;
        }

        /// <summary>
        /// Create auto-generated Nonterminal (must need 
        /// </summary>
        /// <returns></returns>
        public static NonTerminal GetNonTerminal()
        {
            string name = "G" + autoGeneratedIdx++.ToString();

            var result = new NonTerminal(name, false, true);
            keyManager.AllocateUniqueKey(result);

            AutoGenerator.CreateAutoGenerateNT?.Invoke(result);

            return result;
        }
    }
}
