using Parse.FrontEnd.RegularGrammar;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Parse.FrontEnd
{
    public class KeyManager
    {
        private Dictionary<UInt32, string> terminalKeyDic = new Dictionary<uint, string>();
        private Dictionary<UInt32, string> nonTerminalKeyDic = new Dictionary<uint, string>();
        private Dictionary<UInt32, string> meaningUnitKeyDic = new Dictionary<uint, string>();

        private UInt32 terminalKey = 1000000;                   // 1000000 ~ 1999999
        private UInt32 nonTerminalKey = 2000000;            // 2000000 ~ 2999999
        private UInt32 autogeneratedNTKey = 3000000;    // 3000000 ~ 3999999
        private UInt32 meaningUnitKey = 9000000;

        public static UInt32 EndMarkerKey { get; } = 1;
        public static UInt32 EpsilonKey { get; } = 2;
        public static UInt32 NotDefinedKey { get; } = 3;


        public void AllocateUniqueKey(Terminal item)
        {
            if (this.terminalKeyDic.ContainsValue(item.Value))
                item.uniqueKey = this.terminalKeyDic.FirstOrDefault(x => x.Value == item.Value).Key;
            else
            {
                this.terminalKeyDic.Add(terminalKey, item.Value);
                item.uniqueKey = terminalKey++;
            }
        }

        public void AllocateUniqueKey(NonTerminal item)
        {
            if (this.nonTerminalKeyDic.ContainsValue(item.Name))
                item.uniqueKey = this.nonTerminalKeyDic.FirstOrDefault(x => x.Value == item.Name).Key;
            else
            {
                if(item.AutoGenerated)
                {
                    this.nonTerminalKeyDic.Add(this.autogeneratedNTKey, item.Name);
                    item.uniqueKey = this.autogeneratedNTKey++;
                }
                else
                {
                    this.nonTerminalKeyDic.Add(this.nonTerminalKey, item.Name);
                    item.uniqueKey = this.nonTerminalKey++;
                }
            }
        }

        public void AllocateUniqueKey(MeaningUnit item)
        {
            if (this.meaningUnitKeyDic.ContainsValue(item.Name))
                item.uniqueKey = this.meaningUnitKeyDic.FirstOrDefault(x => x.Value == item.Name).Key;
            else
            {
                this.meaningUnitKeyDic.Add(this.meaningUnitKey, item.Name);
                item.uniqueKey = this.meaningUnitKey++;
            }
        }

        public void Remove(NonTerminal nonTerminal)
        {
            var key = this.nonTerminalKeyDic.FirstOrDefault(x => x.Value == nonTerminal.Name).Key;
            this.nonTerminalKeyDic.Remove(key);
        }
    }
}
